### ISSUE TITLE
node-native-zip 压缩文件时,向addFiles方法中添加远程文件(http://siburuxue/....../1472544228848.html)

### ISSUE THREAD

**Issue by siburuxue** [janjongboom/node-native-zip#17]
最近在使用您写的第三方note-native-zip将文件写入Zip 并打包下载，但是在实现功能的时候 发现并不能将远程的文件加入压缩包，查看代码的时候发现在readFile在读取远程文件的时候会异常。末学在异常的部分添加的对远程文件的处理，希望您的下一个版本能将这个功能加入到第三方，这样就不用再远程文件时在额外的写其他的逻辑了。Thank you。

**Comment by janjongboom** [comment]
As said in the readme, this project has been abandoned in favor of node-archiver.

**Comment by siburuxue** [comment]
没注意看readme。。。。。 那我试试node-archiver。Thank you~
