### ISSUE TITLE
Moving away from Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [janjongboom/node-native-zip#18]
The `Buffer` constructor `new Buffer(...)` is deprecated and unsafe. Is it possible to move the [relevant code](https://github.com/janjongboom/node-native-zip/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) to `Buffer.from(...)` instead?

**Comment by janjongboom** [comment]
@gabrielschulhof Long time no see. I realize that this was probably an automated effort, but this repo is outdated and abandoned. There's a depreciation warning on the README already.

**Comment by gabrielschulhof** [comment]
@janjongboom indeed 🙂
